name: Publish
on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish coverage plugin as zip
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: to_version
        uses: actions/github-script@0.9.0
        with:
          result-encoding: string
          script: |
            return '${{ github.event.release.tag_name }}'.replace(/^v/, '');
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - id: cache-gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Test
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s test
      - name: Assemble Dist
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s distZip
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/distributions/test2code-plugin-${{ steps.to_version.outputs.result }}.zip
          asset_name: test2code-plugin-${{ steps.to_version.outputs.result }}.zip
          asset_content_type: application/zip
      - name: Publish to Maven Repo
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: -s publish
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
